### ISSUE TITLE
Better MIME header handling (was: Attachment handling bug)

### ISSUE THREAD

**Issue by Dexus** [haraka/Haraka#1166]
Look to http://www.emailsecuritycheck.net/index.html

http://pastebin.com/xhKSzmvu

http://pastebin.com/PtrfzcHm

http://pastebin.com/PWpfT0VQ

http://pastebin.com/mVL9vHUP

This message should be as it is actually directly rejected because of faulty syntax.

Or should this be blocked by the client?

**Comment by smfreegard** [comment]
@Dexus:  this issue is a bit meaningless without the Haraka logs to go with it (e.g. the output of the 'filename' from the attachment hooks).

Haraka shouldn't reject these unless instructed to by a plugin (e.g. attachment or the like), however if the parser doesn't get the filename correctly, then it would be a bug.

**Comment by smfreegard** [comment]
Add support for https://tools.ietf.org/html/rfc2231
