### ISSUE TITLE
e-mail parsing is modest and to make additional hook and mods useful, it needs a refactoring

### ISSUE THREAD

**Issue by Dexus** [haraka/Haraka#1232]
In recent weeks I have some annoying aspects found on Mailparser.

Unfortunately, some of the methods work inadequately or not. Especially when you need to make edits to the email or wants, the current version is so modest, that I advocate for the mail parser to rewrite or to revert to existing codes, which allow somewhat more leeway.

At the moment I am unfortunately dependent to use https://github.com/andris9/mailparser and https://github.com/andris9/mailcomposer because it our own mail parser fails to make changes.

Of course, you do not have to make it a condition, but some components of it are very helpful and useful.

**Comment by baudehlo** [comment]
This bug is far too vague. Without a sample email that fails to parse, and without any info about what is really desired, I'm going to close it.

I have some potential ideas for changing the contents of body parts when they are text, but that is a much bigger discussion and this ticket is a bad place for that.
