### ISSUE TITLE
Entering body filter in bodies with empty content

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1314]
Hi.

We have a requirement when we need to filter all our emails bodys. We need to change the text of the body in all cases. 

So something like this could do the trick
```js
connection.transaction.add_body_filter('', function(ct, enc, buf){
      return new Buffer("New text");
});
````

It works ok, but in emails without body text (an message with just subject but not content) it does not work. It does not work because Haraka only enters in the body filters if the body `body_text_encoded` has something.

This is because this line https://github.com/haraka/Haraka/blob/master/mailbody.js#L236

It says `if (this.body_text_encoded.length && this.bodytext.length === 0)`.
So, @msimerson @smfreegard would you accept a PR removing the `body_text_encoded.length` condition? I think this is a valid case that body filters should manage.

If not, Would you accept a PR with a setting that dont validate this? How would you call the setting and where save it?

Thanks!

**Comment by baudehlo** [comment]
Sounds good to me.

**Comment by msimerson** [comment]
> would you accept a PR removing the body_text_encoded.length condition? I think this is a valid case that body filters should manage.

Yes, so long as you add test coverage. My concern would be subsequent code that blows up due to assuming there would be some body text to work with.

**Comment by baudehlo** [comment]
Managed to push this to master somehow. Thought that was blocked?

Anyhow, it has tests... So should be good. See d2f08d2

**Comment by msimerson** [comment]
> it has tests... So should be good.

That should close this issue then, right?  And if it doesn't, then we can reopen it.

> Managed to push this to master somehow. Thought that was blocked?

It was. One day, not terribly long ago, when I had a handful of not-mine PRs to merge, and I wanted to avoid a bunch of "Merge branch 'master' into ..." messages in the history, and I didn't want to go through the bother of adding more git remotes to rebase each PR, so I turned off the "Include Administrators" checkbox. That lets the open PRs merge (they've already passed CI tests) but it also disables the desired "disable push to master" feature.

I have sent a help request to GitHub asking if there's a way to configure the "Merge the latest changes from master into this branch" feature to use rebase by default instead of merge. Basically, the equivalent of  `git config --global pull.rebase true`, which does the same as `git pull --rebase` except without having to tack on the --rebase every time.

**Comment by msimerson** [comment]
GitHub response:

> Hi Matt,
> 
> Thanks for reaching out and providing detailed feedback like this -- that's always helpful.
> 
> Currently, there's no way to work around this behavior other than doing the things you mentioned at the  end of your message. The team is considering decoupling this up-to-date requirement from the required status checks requirement so that you can have required statuses without the up-to-date requirement. I can't say when that will happen, but just wanted to let you know it's on our radar.
> 
> I wish I had better news for you, but I don't. If you have any other questions or suggestions -- please let me know.
> 
> Cheers,
> Ivan
