### ISSUE TITLE
Don't require TLS certificate pair when acting as an SMTP client.

### ISSUE THREAD

**Issue by smfreegard** [haraka/Haraka#1324]
Currently we require a tls_[key|cert].pem before we'll send STARTTLS and switch to a secure socket. This is unnecessary when we're acting as a client.

If we have a tls_[key|cert].pem, then we can present it as a client certificate, but it shouldn't be required for TLS to be attempted.

**Comment by baudehlo** [comment]
I'm reading the docs for tls.createSecureContext and it says 'key' is required. I don't know how we achieve this. Any ideas?

**Comment by Dexus** [comment]
We can use PEM and create one... Or some other module...

Von meinem iPhone gesendet

**Comment by smfreegard** [comment]
@baudehlo: it would seem that you can call it without any arguments based on the source:
https://github.com/nodejs/node/blob/master/lib/_tls_legacy.js#L688

As a side note - we could completely do away with our TLS cludges by dropping node 0.10.x support completely as we can then do:

var sock = net.connect(....);
tls.connect({socket: sock}, .... {
   ....
});

Which will update the SMTP client socket to TLS.   On the server end you would use new tls.TLSSocket() to upgrade.

**Comment by celesteking** [comment]
yes dropping stale node versions is a good idea.
Also, what is outbound_load_tls_ini branch about?

**Comment by msimerson** [comment]
Just yesterday I was thinking it's about time to drop 0.10, so I'm +1 on that.

**Comment by baudehlo** [comment]
My only problem is moving up on boxes I control has proved hard due to
requiring a newer compiler than ships. e.g. debian 7.7 won't even compile
node 0.12.

**Comment by baudehlo** [comment]
Also kludges aside - they work and are stable. I'd hate to change code just for the sake of it.

**Comment by msimerson** [comment]
Who is changing code for the sake of it? Switching to `tls.TLSSocket` (#1099) was a response to past issues with our current TLS. It's a better API. The main reason we haven't done it yet (besides a shortage of round tuits), is that it requires dropping node 0.10. But dropping 0.10 also enables #1323, which is also a very nice improvement.

What's preventing you from upgrading your boxes to Debian 8?

**Comment by baudehlo** [comment]
Laziness and fear. I don't have a second box to test an upgrade on, so fear
of downtime while I emergency fix things. Emailitin is now processing over
140k attachments a month for people, so it has become a pretty important
service for them.

**Comment by msimerson** [comment]
>  I don't have a second box to test an upgrade on

Ahh, a precious [snowflake server](http://martinfowler.com/bliki/SnowflakeServer.html).

Inspired and [disappointed](https://blog.abevoelker.com/why-i-dont-use-docker-much-anymore/) by Docker, I've been trying to wean myself off the snowflake server habit, making [my](https://github.com/msimerson/Mail-Toaster-6) production services composable. I've been chipping away at bits here and there for months and I'm half done. For any of (dns, mysql, redis, clamav, avg, spamassassin, rspamd, webmail, haproxy, geoip) services, I can re-deploy with a simple command `provision $serviceName`, and I get a new instance with the latest fully-patched version of FreeBSD, the latest version of the app, the same data as before, and a 1-3 second "downtime" window. When the pooh hits the rotary oscillator, I have the filesystem of the previous instance available so I can revert entirely, or more often, copy over a config file that was missed in the deployment, and then update the provisioning script.

I should have done this years ago.

When its maintanance time, I still have the "old" ways, such as hopping into the VM and running an update command, and now I also have the really big hammer of `provision $service` for when larger updates are required, such as all them openssl exploits or the recent glibc exploit. So far, if I can do it with a single line of bash, then I do it the old way. Anything more and it's easier to provision a new instance.

Part of making the services composable was isolating the data from the applications. Now each service has its own data filesystem (/data/$service) which has all sorts of benefits. /data are the only filesystems on the server needing backups. Migrating to a new host is not much more complicated than provisioning the service on the new host and shipping the data filesystem over with, `zfs send /data/$service | ssh $newHost zfs recv`.

I develop and test the provisioning scripts in a VM on my mac, so by the time I've run them on the server, I'm confident in what it's going to spit out.

All the same things can be done with Docker, using AUFS instead of ZFS, iptables instead of pf, etc. Docker makes some things easier and some harder (its way less mature than jails) but the ideas are all the same. It's more work today to automate provisioning but I'm moderately confident that it's a win in the Long-Term Laziness department.

**Comment by baudehlo** [comment]
Yeah see, I have no time for sysadmin, sadly :(

I should probably just switch to Heroku for my laziness :)

I'll google upgrading Debian - I shouldn't be the hangout holding Haraka
back.

**Comment by celesteking** [comment]
okay, can we get  special non-0.10 branch with these features incorporated? Want to try it out.

**Comment by msimerson** [comment]
I'm thinking about rolling a 2.8.0-alpha.1 release, something that doesn't automatically install when someone does `npm install -g haraka`, but lets us easily specify it for early deployment testing. Maybe I'll get to that today...

**Comment by baudehlo** [comment]
You can try these features out today with non-0.10. I got everything
working last night even on 0.10.

**Comment by msimerson** [comment]
@baudehlo , has your work in #1340 addressed this?  (I think yes)

**Comment by baudehlo** [comment]
Yes as I said in the previous comment - it allows no cert to be used in
outbound TLS. I've tested it - works fine.
