### ISSUE TITLE
Proposal: Run eslint on only one node version

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#1538]
I propose we only run eslint on the latest version of node (whichever we support).

I *think* we can do this in travis config:

Travis has various ways of customising the build:

https://docs.travis-ci.com/user/customizing-the-build/

But I'm not sure how.

A potential easier way is to use the Gruntfile.js to do it.

NB: This came about because eslint stopped working on node v0.10. An obvious easier escape is to drop support for v0.10. But the proposal for this bug might speed up travis checks.

**Comment by msimerson** [comment]
In [the PR I just merged](https://github.com/haraka/Haraka/pull/1535/files), we dropped testing for node 0.10, making only node 4, 5, and 6 tested. I'd be perfectly happy to also drop testing for node 5.0, since upstream support for it is about to expire. I'd much rather maintain node 4 (Long Term Stable) testing until upstream support for it expires.

**Comment by msimerson** [comment]
There may be two separate issues to consider:

1. support for node 0.10
2. automated build testing for node 0.10

What I just merged in #1535 was the latter, because some of our automated testing tools have dropped 0.10 support. Dropping node 0.10 support consists of at least:

* updating some docs
* updating package.json
* ....

**Comment by baudehlo** [comment]
God I really need to upgrade my servers :(

**Comment by msimerson** [comment]
> might speed up travis checks

slightly. The lint checks aren't where our test suite is slow.

````
$ time grunt lint
....
real	0m3.235s
user	0m3.328s
sys	0m0.262s
````

To make our test suite run **much** faster, we'd need to get our test harness to run tests in parallel. I've seen [some](https://github.com/danielstjules/mocha.parallel) [modules](https://github.com/coursera/triple-latte) that will run mocha-like tests in parallel, and I've listened to a MeetUp where an eBay data scientist also wrote his own. Such solutions can make a HUGE difference in how long it takes the test suite to run. Minutes to seconds. There are no such alternatives to [nodeunit](https://github.com/caolan/nodeunit) and there are unlikely to ever be (based on caolan's comments).

**Comment by msimerson** [comment]
I dropped node 5.x testing in package.json as well.

I'm not sure there's anything else to do here, since the issue suggestion won't really affect the desired outcome. Reopen if I've surmized incorrectly.
