### ISSUE TITLE
To remove

### ISSUE THREAD

**Issue by pconihout** [haraka/Haraka#1569]
To remove. Sorry.

**Comment by baudehlo** [comment]
I assume you mean AWS Elastic Beanstalk?

I haven't heard of anyone doing that, but mostly because Haraka is so fast
that it's rare for someone to need auto-scaling, especially because if
you're at the scale where Haraka needs more than one server then you're
probably making a ton of money and can manage your resources yourself.

Furthermore, AWS is terrible for email. They are blocked in a ton of
places, and make it pretty hard to send out from. I suspect the
auto-scaling isn't going to work well for that since outbound SMTP servers
generally need valid rDNS, and auto-scaling rDNS isn't trivial. Also every
AWS IP address that sends email needs to have Amazon whitelist it for email
sending: http://aws.amazon.com/contact-us/ec2-email-limit-request/

Anyhow, generally I think it's probably over-engineering things. Are you
receiving/sending over 20 million emails a day? If you are, I'd love to
hear about it out of band too. If not, this probably comes under YAGNI.

FWIW we have good support for load balancing with HAProxy, which our large
scale users make good use of.

Matt.
