### ISSUE TITLE
Blank spaces error

### ISSUE THREAD

**Issue by ricardopolo** [haraka/Haraka#1583]
After using the new streaming option I am having delivery issues.

Some customers are reporting issues like this:

"Parece que su programa de correo electrónico agregó caracteres no válidos (caracteres de avance de línea vacíos) al mensaje cuando lo envió. Pruebe a usar un programa de correo diferente para enviar el mensaje. Si el problema persiste, envíe este mensaje de informe de no entrega (NDR) a su administrador de correo para obtener ayuda."

I would translate that as the program adds blank breaklines.
The code error is 550 5.6.11 .

Remeber I create the stream using mailcomposer (from nodemailer). When sending with `toString()` the issue does not happen.

**Comment by baudehlo** [comment]
It's probably something simple like dot stuffing.

**Comment by andris9** [comment]
This error is usually for using &lt;LF&gt; line endings instead of &lt;CR&gt;&lt;LF&gt;. No idea if this is the case but Mailcomposer only converts line endings if the mime node content needs encoding (eg. it's a text node that contains non-ascii characters or it's a binary attachment), so if you use a string value with short lines (less than 79 bytes) and only use printable ascii symbols, then the string is passed as is and you might end up with invalid line endings. In Nodemailer context this is not an issue since Nodemailer forces all line endings to &lt;CR&gt;&lt;LF&gt; when sending messages to SMTP.

**Comment by baudehlo** [comment]
Gotcha. Should be an easy fix.

**Comment by ricardopolo** [comment]
Hi @baudehlo have you had time to check this?

Thank you!!

**Comment by baudehlo** [comment]
I haven't, no.

**Comment by ricardopolo** [comment]
@baudehlo it's ok I'll be waiting.

Any test that you need I am available anytime

**Comment by baudehlo** [comment]
I don't think that PR will actually fix it - I don't think @andris9 's summary is correct here, as we pipe the data into a MessageStream object, which does the dot stuffing and line ending fixups.

So I'm once again lost, unless you can replicate this for me with some sort of test.

**Comment by celesteking** [comment]
Need a sample message to replicate or a test email. Let's close this otherwise.

**Comment by msimerson** [comment]
Closing. There's little we can do here without a test case.
