### ISSUE TITLE
Skipping over attachments with round brackets in boundary

### ISSUE THREAD

**Issue by dstibrany** [haraka/Haraka#1874]
### system info
Ubuntu 14.04
Node v4.6.1
Haraka v2.8.12

### Observed behavior

We have a client whose multipart message has a boundary of `nqp=nb64=()I9WT8XjoN`. The `()` in the boundary is causing Haraka to skip over the included attachments. Looks like it's from this line https://github.com/haraka/Haraka/blob/51c01f7690a4bf32dcab4f4c3b4ab0e270f0f508/mailheader.js#L175

Wondering if this is a bug in Haraka or if the client is doing something bizarre.

**Comment by baudehlo** [comment]
It's a bug, due to the naivety of the comment stripping. The boundary value
can have brackets in which aren't comments.

To do this properly we'd have to follow all the rules of the various RFCs
for every single header value, and that gets complex fast (you need a
proper parser).

It might be better to just take out that line and leave comments in.
@msimerson thoughts?

**Comment by msimerson** [comment]
Perchance can you include the actual raw header of the message? That's the sort of thing that belongs in our test suite, so that when this gets addressed, it doesn't recur.

**Comment by msimerson** [comment]
Presumably it's something like this, right? `Content-Type: multipart/alternative; boundary=nqp=nb64=()I9WT8XjoN`

**Comment by baudehlo** [comment]
It would have to have quote but yes I would guess so.

**Comment by dstibrany** [comment]
`Content-Type: multipart/mixed; boundary="nqp=nb64=()I9WT8XjoN"`
