### ISSUE TITLE
Control the outbound traffic by time

### ISSUE THREAD

**Issue by acharkizakaria** [haraka/Haraka#2006]
Hi guys, Is there any "plugin/config" that gives us the ability to control the outbound traffics by time ?

For example if I want to send 10 mails in by second :

- 10/1000 : Will deliver just 10 mails in every second, even if the queue has 500 mail for example.

Thanks in advance.

**Comment by baudehlo** [comment]
See the rate_limit plugin.

**Comment by acharkizakaria** [comment]
I'm trying to use the new plugin **_'haraka-plugin-limit'_** comes with v2.8.13 , as the changes file says :

**Changes 2.8.13 - Feb 03, 2017 :**
* new [haraka-plugin-limit](https://github.com/haraka/haraka-plugin-limit) #1785
     * replaces plugin/limit, plugin/rate_limit, and haraka-plugin-outbound-rate-limit

I'm having  a problem during the implementation, the plugin seems to work just for the first time for the outbound part.

**Example :**

If I'm using the following Config in _**limit.ini**_ : 

```
[outbound]
enabled=true
domain=1
delay=10
```
Then queuing 5 mails. 

**Expected :**
Deliver 1 mail every 10 seconds.

**Current behaviour :**
Deliver the first mail then delayed the rest '4' mails for 10 seconds (as expected), but after the first 10 seconds the _'send_mail'_ hook will be called and delayed the '4' mails another time and keep delay them every 10 seconds... without delivering.

Thanks in advance.

**Comment by msimerson** [comment]
This is really a bug with the current outbound rate limits implemented over in [haraka-plugin-limit](https://github.com/haraka/haraka-plugin-limit). I noticed most of the rate limits were poorly implemented this way. I [reimplemented](https://github.com/haraka/haraka-plugin-limit/commit/330d6c3e768ab0dfbf11c61486165f2e346932c9) the ones I wanted to use so that they work as you'd expect.

I'm closing this PR because it should be filed in the haraka-plugin-limit repo. Feel free to re-open it over there. Better still, have a look at my changes to the other rate_limits and open a PR that does the same for outbound.

**Comment by acharkizakaria** [comment]
Sorry @msimerson I've opened a new issue in the plugin repository https://github.com/haraka/haraka-plugin-limit/issues/6.

I've tried to follow up the above given implementation with no success :(

**Comment by msimerson** [comment]
No worries, that's the right thing to do. That way someone else who has the same need will find that issue in the right place.
