### ISSUE TITLE
Hacktoberfest: Should we add one Changes.md line per change?

### ISSUE THREAD

**Issue by baudehlo** [haraka/Haraka#2164]
There seems to be a bunch of changes coming in for Hacktoberfest. It doesn't seem useful to add one line to Changes.md for every file that gets changed.

Preferences/Thoughts?

**Comment by msimerson** [comment]
updating Changes.md with each PR has the side effect of creating lots of merge conflicts. They're easy enough to fix, but it's less than optimal.

A wonderful (if it worked) solution would be editing the merge title and description **consistently and well** during every merge, such that a script could just prepend all the changes to Changes.md as part of the release process. I've been a lot of conscientious lately when merging, so that I can **normally** just copy/paste PR descriptions into Changes when releasing. But it's still tedious and manual.

**Comment by KingNoosh** [comment]
I think we'll just edit the PR title, at the end of hacktoberfest we'll go through and collate all the related PRs under a `Clean Up` section of the changelog or something like that?

**Comment by msimerson** [comment]
Conversation stalled, closing issue.
