### ISSUE TITLE
why use first label of os.hostname instead of config/me?

### ISSUE THREAD

**Issue by msimerson** [haraka/Haraka#2168]
[here](https://github.com/haraka/Haraka/blob/master/connection.js#L564-L569) in connection.js we use the first label of the result of `os.hostname()` instead of the hostname from `config/me`. 

- Why?
- Should we?

**Comment by baudehlo** [comment]
Why: I probably copied it from qpsmtpd.
Should we: probably not.

**Comment by smfreegard** [comment]
> Why: I probably copied it from qpsmtpd.

According to blame, I added it a couple of years ago.   IIRC it was added to help people running clusters of Haraka (e.g. Craigslist) so that if they get a rejection report, they could see which host did the rejection.   I made it the first label of the hostname for brevity as we're space limited.

The only reason I can think of for not using `config/me` was to handle the case where a cluster might all set the same `config/me` value, but you'd want to report the actual hostname here instead.

> Should we?

(shrugs)
