### ISSUE TITLE
Still conversion of es6 not happened quite clearly

### ISSUE THREAD

**Issue by Hari70a** [haraka/Haraka#2235]
I feel that just  `var` was replaced by `const`, `let `and `class`.It doesn't have `import `statements.Instead of that ,it's just replaced `var `with `const `and `let`.Also there is still '`use-strict'` which is not actually needed in es6  and es7

**Comment by msimerson** [comment]
> Also there is still 'use-strict' which is not actually needed in es6 and es7

We aren't es6 **exclusive**. Yet. We're taking advantage of es6 features that are available in node 6+.

**Comment by KingNoosh** [comment]
It's a slow process updating syntax and making sure stuff still works. I'm aware `import` exists in node 6 so I'm going to start looking at that at some point. If you have any suggestions, throw them at us just in case.
;)

**Comment by MuraraAllan** [comment]
We have to pay attention in ECMA Standards (https://www.ecma-international.org/publications/standards/Ecma-262.htm here is general and es8 release notes, from July) x Node Engine.

Actually node doesn't support import. You need to transpile it in order to be able to use the import syntax, what doesn't mean you should apply to Haraka. Actually i don't see Haraka using it.

I strongly recommend you to read this one @Hari70a . It should be enough to clarify the principle of Synchronous / Asynchronous module load on NodeJS.

https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c

**Comment by KingNoosh** [comment]
Import is in node 6+, we use it at my workplace in our plugins for Haraka.

**Comment by MuraraAllan** [comment]
Are you sure you are not transpiling it with babel ?

**Comment by MuraraAllan** [comment]
I searched here to find the Octobers last tc-39 reunion article.

This is node contributor article : https://hackernoon.com/node-js-tc-39-and-modules-a1118aecf95e

If you use babel in Haraka, will result in some performance gap IMO, i could help implementing babel to test performance, but i'm pretty sure that node itself doesn't support import/export without a transpiler as in both articles from node contributor says.

Its a trick question and that is why react uses Babel for bunch of things.

**Comment by MuraraAllan** [comment]
https://hackernoon.com/node-js-tc-39-and-modules-a1118aecf95e 


"For Node.js, a challenge arises when “foo” is not a ESM with a lexically defined set of exports, but a CommonJS module with a dynamically defined set of exports. Specifically: when I say import {m} from “foo”, ESM currently requires that it is possible to determine that m is exported by “foo” before evaluation; but as we’ve already seen, since “foo” is a CommonJS module, it is not possible to determine that m is exported until after evaluation. The end result is that named exports and imports from CommonJS, a critically important feature of ECMAScript modules, simply would not be possible under the currently defined ESM specification."

They are still working over it, this topic is from october begining, aren't you using Babel @KingNoosh ?\

**Comment by KingNoosh** [comment]
We don't use Babel.

**Comment by Hari70a** [comment]
@MuraraAllan  
I have read the link
[https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c](https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c)

**Comment by KingNoosh** [comment]
Adding another pointless build step isn't needed. If Haraka was completely rewritten, sure I'd consider Babel or even TypeScript, but not for an on-going project.

Personally, I'm going to support whatever is green for the most up to date LTS version of Node.

**Comment by msimerson** [comment]
> Personally, I'm going to support whatever is green for the most up to date LTS version of Node.

+1

**Comment by msimerson** [comment]
But with caveats for Harara, because there are significant costs to churn. I like to use node.green features in small doses until I grok them.
