### ISSUE TITLE
Unrecognized command: STARTTLS.

### ISSUE THREAD

**Issue by MrSorcus** [haraka/Haraka#2300]
### system info

Haraka | Haraka.js — Version: 2.8.16
 --- | :--- 
Node | v6.11.3
OS | Linux server.inwebse.org 3.10.0-693.5.2.el7.x86_64 #1 SMP Fri Oct 20 20:32:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.2k-fips  26 Jan 2017

### Logs (loglevel: DEBUG)
https://gist.github.com/MrSorcus/30ef6515d2603f750dd2062ef2c5aa15

I get error with STARTTLS, but here https://www.checktls.com/perl/live/TestReceiver.pl no error.
All columns is green. (for address undefined@inwebse.com)

**Comment by smfreegard** [comment]
This isn't a bug.   It's expected behaviour.   STARTTLS is not a native command to Haraka, it's implemented by a plugin using the unrecognized_command hook.

The problem you have here is with the max_unrecognized_commands plugin and is due to you loading that plugin before the tls plugin, so the max_unrecognized_commands plugin thinks the STARTTLS command was unknown, when what actually happened is that the tls plugin handled it afterwards.

What you need to do is move max_unrecognized_commands after tls in `config/plugins` and it will work correctly.  Note that plugins are run in the order listed in `config/plugins`, so ordering is critical for things like this.

You can see the order of plugins on each hook by running `haraka -c /path/to/config/dir -o`
