### ISSUE TITLE
restart Haraka service when it down.

### ISSUE THREAD

**Issue by zinwalin** [haraka/Haraka#2362]
which tool do well with Haraka?   there're some options, 

supervisor,  forever ...

**Comment by KingNoosh** [comment]
We have Haraka in a docker container and we have it set to autorestart when
it crashes or exits.

**Comment by baudehlo** [comment]
Due to the nature of what it has to do, Haraka implements it's own restart
functionality in case of a crash. Just set nodes=cpus in smtp.ini and it'll
"Just Work" (assuming the master process doesn't crash).

supervisor, forever and pm2 are entirely unsuitable for Haraka. You want
something like systemd or runit instead. If you use those, the master
process is protected from crashes too.
