### ISSUE TITLE
Unverified domain rejection.?

### ISSUE THREAD

**Issue by ashucharm** [haraka/Haraka#2400]
Hi,

I'm using haraka latest version 

My some domain are not verified (SPF and DKIM) and i want to reject mailing from this domains.
Until the verified.

Thanks in advance

**Comment by noogen** [comment]
I also just did this in a plugin for DKIM validation - https://github.com/niiknow/dockers/blob/master/haraka/rootfs/sysprepz/plugins/dkim_bouncer.js#L78

**Comment by msimerson** [comment]
Hey @noogen, looks good. However, be warned that you risk rejecting a bunch of valid mail by comparing just DKIM failures. An example of valid email that often has broken DKIM signatures is email list traffic. I haven't measured recently but the last time I did (about 2 years ago) about 10% of valid mail traffic had broken DKIM for one reason or another. That should have gotten much better as email lists updated their software to not break the DKIM signatures. That's also partly why DMARC exists, it validates the sending domain using SPF **or** DKIM. Normally both pass for valid mails, but for the edge cases where SPF or DKIM fail, the failures don't overlap so you can expect at least one of SPF or DKIM to pass for every valid message.

**Comment by noogen** [comment]
Hi @msimerson, if I understand correctly, your plugin handle both inbound and outbound verification.  *My question is, if I'm only handling authenticated user outbound email, would my plugin work?*  

Hence, I'm only binding to hook_queue_outbound.  I do make a couple of naive assumptions on my use-case:
1.  I'm only allowing authenticated user to send email from our Haraka server.
2. To use custom email domain, authenticated user must setup both SPF and DKIM correctly in their DNS - otherwise, I'm rejecting their email even before sending it out.
3.  I'm providing the same DKIM and selector to all my users, hence symbolic link: https://github.com/niiknow/dockers/blob/master/haraka/rootfs/sysprepz/plugins/dkim_bouncer.js#L42

Again, if I'm only handling authenticated user outbound email, would my method work?  Thanks

**Comment by bunyevacz** [comment]
Is it possible to force dkim verification for certain domains?

We get tons of spam, where FROM and TO matches the user email address.
Typically the email goes like this: 
```
From: myself@mydomain.com
To: myself@mydomain.com
Subject: Your account has been hacked.
```
We send out all email (zone-mta) dkim signed. I also set spf for the domain.
So I could force to accept emails for our domain (mydomain.com) IF the message itself has a valid dkim signature (ie. we sent it in the first place:)

I also would like to force DKIM verification for all `@gmail.com` domain. Seems like gmail also signes all their outgoing emails.

That would cut our amount of spam by half.

**Comment by ad-m** [comment]
> I also would like to force DKIM verification for all @gmail.com email addresses. Seems like gmail also signes all their outgoing emails.
This is what DMARC was invented for.

**Comment by bunyevacz** [comment]
@ad-m: I have correctly set DMARC dns TXT field for our domain. The question is still open.
I'm looking into the [dkim_bouncer.js](https://github.com/niiknow/dockers/blob/master/haraka/rootfs/sysprepz/plugins/dkim_bouncer.js#L85) maybe I can come up with something usable.

Or am I missing something obvious? Can you link to the documentation, if DMARC dns field is respected out of the box by haraka?

**Comment by msimerson** [comment]
There isn't (yet) a DMARC plugin written for Haraka. Well, not a complete one anyway. I did scratch together a [quick and dirty DMARC plugin](https://github.com/haraka/Haraka/pull/452) that uses Mail::DMARC (a perl DMARC verifier I wrote).

**Comment by msimerson** [comment]
I tidied up my DMARC plugin, packaged it as an NPM module and [published it on NPM](https://github.com/haraka/haraka-plugin-dmarc-perl). It still requires you to run the HTTP service from Mail::DMARC. It'll have to do until someone spends the time to write a native JS version.
