### ISSUE TITLE
label:help wanted

### ISSUE THREAD

**Issue by 1smrtdude** [haraka/Haraka#2464]
### system info

Using as edge MTA to deliver mail to and from internal MTA.

Plugins: helo.checks, tls, auth/flat_file, mail_from.is_resolvable, rcpt_to.in_host_list, data.headers, queue/smtp_forward, limit

Config is working, all mail flows in and out as expected until artificially making internal mail server unavailable.

### Expected behavior

When destination MTA is unavailable, Haraka queues mail and retries until it comes back online.

### Observed behavior

When destination MTA is unavailable, Haraka replies DENYSOFT connection to originating MTA.

### Steps to reproduce

Artificially make internal MTA unavailable and send an email to a mailbox on that MTA that first passed through MTA. All attempts to deliver message to domain forwarded by Haraka result in DENYSOFT reply to originating MTA.

**Comment by msimerson** [comment]
This is the expected and desired behavior when using smtp_forward. If you want Haraka to queue and then retry when the destination is available, then you want to queue to `outbound` instead.

**Comment by 1smrtdude** [comment]
So outbound can handle mail coming to AND from my internal MTA?

**Comment by msimerson** [comment]
Yes it can. But just as with smtp_forward, outbound may need instructions for how to deliver to your inbound MTA. Outbound defaults to MX based routing. There are various ways to achieve this. The most common are configuring split horizon DNS (so Haraka gets the internal IP for your internal server when it does a MX lookup). I configure smtp_forward with `enable_outbound=true` and use per-domain config blocks.

**Comment by 1smrtdude** [comment]
So I can use smtp_forward as I am by adding enable_outbound=true to the top of the smtp_forward.ini file and it will queue incoming mail if my server is offline?

**Comment by msimerson** [comment]
Sorry I haven’t gotten back yet, I keep intending to. The short version is that my recipient verification plugin(s) set queue.wants to specify which queue mechanism to use. Verified mailboxes get `queue.wants=lmtp`, non-local gets outbound, and others get smtp_forward.

**Comment by msimerson** [comment]
The plugins I use for recipient validation are [haraka-plugin-qmail-deliverable](https://github.com/haraka/haraka-plugin-qmail-deliverable) and `queue/smtp_forward`. You can inspect it to see how it sets `notes.queue.wants=lmtp` for mailboxes and `notes.queue.wants=smtp_forward`for other types such as alias, forward, or mailing list.

**Comment by msimerson** [comment]
more: I also do filtering for other mail servers, and some of those (Exchange) servers don't expose LDAP to me, so I can't verify the username portion of the email address. In cases like that, I use only smtp_forward, because invalid mail recipients will get rejected during the queue phase and I won't get stuck with them in my mail queue.

**Comment by 1smrtdude** [comment]
Thank you for that. My situation is similar to the second option I would assume. My MTA is Postfix, not sure if it supports recipient validation. Both the examples you mention queue mail if the destination server is offline?

**Comment by msimerson** [comment]
In the first case (validated mailbox), I queue mail to outbound regardless of the destinations availability. In the latter case (smtp_forward) I do not because I refuse to accept mail unless I'm certain the next hop will accept it.

You can achieve this a couple ways:
* by setting `enable_outbound=true` in smtp_forward.ini
* a plugin that handles recipient validation (against whatever data source your Postfix server is checking) and then sets `notes.queue.wants=outbound` for validated recipients. Having done so, those messages will get queued to outbound which will handle delivery to the next hop (your postfix server).

**Comment by 1smrtdude** [comment]
Matt,

If it is not a lot of trouble would you be willing and able to provide configuration file examples for me to follow? I'm really just not getting this. Maybe there's some reading I need to do to understand Haraka better...

**Comment by msimerson** [comment]
Okay, this smtp_forward.ini file should do it:

```ini
host=IP.ADDRESS.OF.POSTFIX
port=25
enable_outbound=true
```
