### ISSUE TITLE
Haraka scaling

### ISSUE THREAD

**Issue by Jegannathan** [haraka/Haraka#2484]
System info

Ubuntu 16.04
Node 8.11.1
Haraka 2.8.14

Kindly guide me how to scale haraka through nginx

**Comment by KingNoosh** [comment]
What exact part of Haraka do you actually want to scale?

**Comment by Jegannathan** [comment]
We cannot increase the CPUs . we need to do horizontal scaling.is there a possible way?

**Comment by smfreegard** [comment]
Firstly you need to configure each Haraka installation for maximum performance as per the guide I already posted (e.g. use nodes=cpus etc.).

Then you've got multiple options:

1)  DNS load-balancing.

e.g. publish your MX records with multiple A records e.g.:

IN MX 10  mx1.example.com.
IN MX 10  mx2.example.com.

mx1.example.com.  5 IN A  1.2.3.4
                                5 IN A  4.3.2.1

mx2.example.com  5 IN A 4.3.2.1
                               5 IN A 1.2.3.4

You can add as many A records as you like to each and the DNS will cycle through them which will effectively give you a poor mans load-balancer and will work provided at least one of the IP addresses works.

2)  A proxy that supports the HAProxy PROXY protocol (version 1, not version 2).

You would combine this with method 1) e.g. you would have two load balancers (for redundancy) and load balance those using method 1).

Then configure the proxy to send the PROXY protocol to the Haraka instances  (see the documentation; you have to set config/haproxy_hosts with the IP addresses of the load balancers.   This is required so that Haraka uses the IP address of the host connecting to the proxy instead of the proxy's IP address to ensure that things like DNSBLs and rate-limiting work correctly.

You would have to configure the proxy for maximum performance according it it's documentation; that's beyond the scope of what we can assist with here.

Hope that helps.

**Comment by smfreegard** [comment]
Oh - and obviously - it goes without saying that  you have to keep all of the Haraka configuration in-sync between each of the Haraka nodes.

**Comment by msimerson** [comment]
What Steve said.

**Comment by stevensedory** [comment]
> 
> 
> Oh - and obviously - it goes without saying that you have to keep all of the Haraka configuration in-sync between each of the Haraka nodes.

Could you please point me to where I can read about configuration syncing between nodes? Or is just manually keeping the configurations the same enough?

**Comment by gnanaprakash** [comment]
@smfreegard @msimerson I'm just getting started with Haraka, and everything seems to be going well so far. I was trying to get into the scaling aspect, and as @stevensedory mentioned, I'm wondering where in the docs I can find the Haraka nodes syncing feature? any updates on this thread would be extremely helpful for new users like me.    

**Btw, good job to the entire Haraka team!**
