### ISSUE TITLE
Haraka sending stats issue.

### ISSUE THREAD

**Issue by Manishjodhani** [haraka/Haraka#2486]
### system info
Haraka | Haraka.js — Version: 2.8.18
 --- | :---
Node | v9.11.1
OS | Linux vps177316.vps.ovh.ca 2.6.32-696.23.1.el6.x86_64 #1 SMP Tue Mar 13 22:44:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
openssl | OpenSSL 1.0.1e-fips 11 Feb 2013

We are using outlook application for sending mail. And when we send mails and add some mail id in CC.
Then it count as one mail was send at that time and in sending stats there is also stats of single mail id.
For example 
To :abc@gmail.com , abcd@gmail.com 
CC : Bcd@gmail.com
From : dcsa@domain.com
Mail were delivered to all mails id's . But when i check the stats it show only first mail id result not the other mails id's.
And some time first mail(XXX@gmail.com) was bounce but other mails were delivered(YYYY@gmail.com) then it will show as bounce.

Please help me out.

Thanks in Advance

**Comment by analogic** [comment]
Try outbound.ini -> always_split=true

**Comment by Manishjodhani** [comment]
Thanks for the reply.
But it's not working. could i change anything else??

**Comment by baudehlo** [comment]
Where are you looking at stats?

**Comment by Manishjodhani** [comment]
Haraka log.
tail -f /var/log/haraka.log

**Comment by baudehlo** [comment]
I recommend using the process-title plugin for gathering stats rather than
looking at the logs.

**Comment by Manishjodhani** [comment]
I will try this plugin.
Can  you help me in one more thing.please have look in screenshot.
![log_1](https://user-images.githubusercontent.com/28861157/43700354-e957cf7e-996f-11e8-86cb-103bdd974ac0.png)
When i send to two mails at same time then it haraka create same uuid for both recipient.(CC)
Is that possible to have different uuid for every recipient (CC) we send.?

**Comment by smfreegard** [comment]
You don't seem to understand how SMTP works.  A connection can have multiple SMTP transactions and each transaction can contain multiple recipients in multiple domains for a single message - that's how it works.

If someone sends you a message that was addressed to multiple recipients at your domain, then by far the most efficient way is to send you the single message with multiple recipients otherwise it would require rcpts * message_size of bandwidth and all the additional I/O required on both ends to deal with that.

> When i send to two mails at same time then it haraka create same uuid for both recipient.(CC)
Is that possible to have different uuid for every recipient (CC) we send.?

Basically - the answer to this is No.

You can *force* the sender to split the message into single recipient messages, however this will cause potentially significant delays.  e.g. if the sending system has a 15m queue interval (which is typical) and they send you a message with 5 recipients, then the first recipient will be received immediately, the 2nd after 15 minutes etc. with the 5 being received after an hour delay.

You can achieve that with the following code:

`````
exports.hook_rcpt = function (next, connection) {
    var txn = connection.transaction;
    if (txn.rcpt_to.length > 1) return next(DENYSOFT, 'Only one recipient at a time please');
    return next();
}
`````

I don't really see what your issue is.   If you treat the SMTP Tranasaction ID *AND* the recipient address as the 'key' - you can track everything from reception to delivery...

**Comment by Manishjodhani** [comment]
Hi, @smfreegard 
Let me explain you. I'm using outlook application and as smtp server i'm using haraka.
And now when i sent mails with outlook using" , " seperate mail id's like this 

To :abc@gmail.com , abcd@gmail.com
CC : Bcd@gmail.com
From : dcsa@domain.com

Then in haraka stats there is only delivered stats of abc@gmail.com this mail id and there were nothing about second mail id.

And we are checking stats in /var/log/haraka.log 

we need all stats of every mail id's

**Comment by msimerson** [comment]
@smfreegard 's answer is complete and correct. We aren't likely to add a config option like: `deliver_every_recipient_in_a_unique_transaction_so_that_Manishjodhani_doesn't_need_to_learn_how_to_extract_the_data_he_wants_from_the_logs`.
