### ISSUE TITLE
outbound section in config/tls.ini not understood?

### ISSUE THREAD

**Issue by pvagner** [haraka/Haraka#2493]
### system info

Haraka | Haraka.js — Version: 2.8.21
 --- | :--- 
Node | v10.8.0
OS | Linux vps.domain.tld 3.16.6-042stab127.46 #1 SMP Wed Mar 28 01:57:40 CEST 2018 x86_64 GNU/Linux
openssl | OpenSSL 1.1.0h  27 Mar 2018

### Expected behavior
I am looking for a way to use different TLS certificates for inbound connections and different for outbound connections.
I do have single server with two domains pointing to it.
vps.domain.tld and mail.domain.tld.
I like to use mail.domain.tld certificate for incoming connections to port 587 that I can configure in my email client to submit mails.
However when delivering the emails to other mail servers in the universe I'd like to present vps.domain.tld certificate.

### Observed behavior
Although I have two sets of TLS certificates in my config/tls.ini one at the top and the other in the [outbound] section at the end Haraka only loads certificates specified outside a section.
Here is the log from another instance of haraka running on the same machine the haraka instance I am trying to configure like this connects to.
https://privatebin.net/?73d5512cef671a1c#iGEa0BgZFD8T6rs5dEd7Yh2tCYKuFkWQdVMMJjSKruk=
And the hostname of the connecting machine vps.domain.tld does not match common name mail.domain.tld in its client certificate despite I'm trying to setup it like this in config/tls.ini.
Am I missunderstanding or making some kind of error or might this be a real issue?

### Steps to reproduce
```
# config/tls.ini
key=mail.domain.tld_privkey.pem
cert=mail.domain.tld_fullchain.pem
dhparam=ssl-dhparams.pem
requestCert=false

[outbound]
key=vps.domain.tld_privkey.pem
cert=vps.domain.tld_fullchain.pem
dhparam=ssl-dhparams.pem
```
And make the haraka to send some emails to the outside world.

**Comment by analogic** [comment]
Please try define **[inbound]** section. Mixing implicit [main] and [outbound] will not work...

**Comment by pvagner** [comment]
If I have no implicit [main] section only [inbound] and [outbound] sections, start tls is not advertised for incoming smtp connections i.e. mail submissions from email clients.

**Comment by analogic** [comment]
See trough the debug logs, if starttls is not advertised but configured there is most probably problem with loading certs

**Comment by msimerson** [comment]
A few tidbits: 

1. What you're trying to do should work, and your config looks fine.
2. The privatebin logs have expired/been deleted. It's better to use gists.
3. You do have an implicit `[main]` section. Anything in an ini that doesn't have a `[declaration]` before it is in `[main]`.
4. Use `openssl s_client -connect mail.mydomain.com:587 -starttls smtp` and show us the output to test if your inbound is working the way you expect.
5. Send a mail to another server that logs TLS cert info and see if your outbound is working the way you expect.
6. Dovecot 2.3 has a new [Submission](https://wiki2.dovecot.org/Submission) agent that will use the same TLS config as the rest of your MUA (assuming you use dovecot). 

Since there's no logs and no evidence that your config isn't doing what you wanted, there's nothing more than can be done here. Closing until further posts demonstrate Haraka isn't doing what it should.
