### ISSUE TITLE
Can we re-spool?

### ISSUE THREAD

**Issue by thenitai** [haraka/Haraka#2505]
Quick question as I have not found anything online, but can we re-spool files from the spool directory?

I see that they are all .eml files, so I take it I can create it and drop it into the spool directory and Haraka should be able to pick it up and send the email, no?

**Comment by baudehlo** [comment]
Not sure what you mean by this ticket. Haraka doesn't save any .eml files unless you enable the queue/maildir plugin, which is only for test purposes. So no, we can't re-queue those files.

**Comment by thenitai** [comment]
We have the "spool_dir" enabled, i.e., spool_after=0

However, when the SMTP server crashes or we need to stop it, shouldn't Haraka pick up those files again and send them out? Hence also my question.

Thank you.

**Comment by baudehlo** [comment]
Oh I see. No, those files are just temporary storage of incoming mail prior
to us sending the final "250 OK" back to the sending client - it's there so
we don't gobble up all your RAM. If we re-spooled them on startup you'd
effectively have duplicate mails (because if the sending server doesn't see
a 250 OK, it's supposed to try again later).

**Comment by thenitai** [comment]
Got it. So, when the server crashed while sending there is no way to re-send it, correct? I guess, I know the answer :)

**Comment by baudehlo** [comment]
If Haraka crashes while sending it will re-send it. There's no
configuration required for that. That spool_dir is not for email haraka is
SENDING, it's for email haraka is RECEIVING. It's up to the remote end to
re-send it to your haraka.
