### ISSUE TITLE
multiple plugins with the same hook running in parallel?

### ISSUE THREAD

**Issue by apmcodes** [haraka/Haraka#2527]
As per the doc, multiple plugins of a single hook run in the order included or specified priority. 

But, with next() inside a setTimeout (trying to simulate delay) in the first plugin causes the below error.
[CRIT] [-] [core] Error: We are already running hooks! Fatal error!

It looks the second plugin is trying to run before the next() of first plugin. Is this something to do with setTimeout and nodejs event loop? 

Can you please clarify/ confirm the below situations (2 plugins of the same hook)
1) If plugin1 is taking time due to waiting for IO/ redis, still plugin2 will begin only after plugin1 
 finishes?

2) With multiple incoming connections, will all the plugins of a hook completes before running with the next connection? Or the below order might happen?

connection1 - plugin1
connection2 - plugin1
connection1 - plugin2
connection2 - plugin2

Thanks.

**Comment by baudehlo** [comment]
Show some code. You've done something wrong.

**Comment by apmcodes** [comment]
Sure.

plugin1
exports.register = function() {
    var plugin = this;
    plugin.register_hook('task',  'plugin1');
}
exports.plugin1 = function (next, qjob, message) {
    this.loginfo(this.name);
    const finishDelay = (Math.floor(Math.random() * 2) + 0) * 1000;
    setTimeout(() => {
        next();
    }, finishDelay);
}

plugin2
exports.register = function() {
    var plugin = this;
    plugin.register_hook('task',  'plugin2',);
}

exports.plugin2 = function (next, qjob, message) {
    this.loginfo(this.name);
    return next();
}

**Comment by apmcodes** [comment]
forgot to do format my post, thanks @msimerson

**Comment by msimerson** [comment]
Yeah, I can read it now without my eyes bleeding. Unless I'm missing something, what you've posted there **should** work.

**Comment by smfreegard** [comment]
What hooks are these plugins running on?

**Comment by apmcodes** [comment]
i have created a custom hook called task which is run after init_server

**Comment by apmcodes** [comment]
Testing with unmodified Haraka (Haraka.js — Version: 2.8.21), works fine with setTimeout as expected. Plugin2 wait for Plugin1 to complete with setTimeout.

So, its my modification that causing this error. Huh ... How am I going to debug this and make it work ... 
:‑( :(

**Comment by baudehlo** [comment]
Callbacks and node concurrency is often confusing. We really can’t help you if you modified Haraka to support a custom hook. It sounds like you might be using some sort of global variable and that’s screwing things up. Always store things on either connection.notes or transaction.notes instead. But beyond that advice we are going to have to close this ticket because we can’t access all your code.

**Comment by smfreegard** [comment]
One final comment - the hook and plugin system expects hooks to run one-at-a-time and you're getting this error because you've got multiple different hooks running at once.

So if your hook is running after init_master, then you either need to prevent the server from starting or continuing until your hook has completed, or you can simply add this hook to the list of other hooks that can run at any time.   You can find this code in plugins.js near to where the error is generated.
