### ISSUE TITLE
Official node Docker images

### ISSUE THREAD

**Issue by AuspeXeu** [haraka/Haraka#2557]
Why not use one of the official docker images as base for the Dockerfile?

**Comment by msimerson** [comment]
Docker isn't supported by @haraka/core. If you wish, submit a PR suggesting the change you want to see.

**Comment by msimerson** [comment]
The core committers of Haraka. We don’t officially support Docker. You’re welcome to ask questions like the one you did, but rather than creating an issue for us to ignore (or hastily close when someone is on an issue cleanup binge), look at the people who have contributed to the Dockerfile. Then pick one of the PRs that edited the file and ping the maintainers of there with your question.
