### ISSUE TITLE
Per IP and Port Plugin Activation/Configuration

### ISSUE THREAD

**Issue by chlarsen** [haraka/Haraka#2633]
### system info

Haraka: 2.8.24
Node: 11.13.0
OS: FreeBSD mail 12.0-RELEASE-p3 FreeBSD 12.0-RELEASE-p3 GENERIC amd64
OpenSSL: OpenSSL 1.1.1a-freebsd 20 Nov 2018

### Expected behavior

Rather: Desired behaviour: 
Port and/or server specific plugin configurationj, without the need to run separate Haraka instances.

### Observed behavior

Plugin configuration is currently applied across all listening IPs and ports, unless I missed something.

### Steps to reproduce

Standard configuration

Any ideas, comments? This could make it easy to have plugins for MTA and MSA roles...
Thank you,
Chris

**Comment by msimerson** [comment]
> Plugin configuration is currently applied across all listening IPs and ports, unless I missed something.

Works as designed.

A standard practice is to run one Haraka as MSA and another at MTA. Configure each for their roles.

Another standard practice is to run one Haraka for both. I do this and it works well for me.

I started exploring [Dovecot MSA](https://wiki2.dovecot.org/Submission). I got it working but haven't had time to test it enough to deploy in production.

**Comment by chlarsen** [comment]
I realise that. The two instances, one for MTA, another one for MSA, works and is the cleanest option, because authenticated users do not have to bear with greet delays and such., while still benefitting from virus scanning, etc. If I ave one shared instance for MSA and MTA functionality, I actually end up with using MORE time as an authenticated user to send mail out than it take to receive mail from a legit third-party domain - not ideal and redundant.
In our setting, we have to look very closely at the resources used for the functionality offered, as we operate in strictly resource-limited environments, enve the separate MTA/MSA approach is not desirable. 
I therefore maintain the notion that it would be desirable to have per IP ad per port, or at least per port allocatable plugins. This would render the system act in a slimmer and more elegant manner. I would appreciate, if this issue could remain open to accommodate users in less privileged environments. Thank you!

**Comment by msimerson** [comment]
> it would be desirable to have per IP ad per port, or at least per port allocatable plugins

There are many other priorities in the [queue](https://github.com/haraka/Haraka/wiki/TODO) that Haraka's active developers would do first. This is highly unlikely to ever happen. Especially since it can already be mostly achieved by configuring Haraka well. I say mostly because I still delay AUTH for MSA traffic, to limit brute force password attacks.

If you really cared about operating in resource constrained environments, dovecot MSA or postfix are both far lighter than Haraka could ever be.

Now, if you happen to write an elegant new plugin loader that provides this feature and is both cleaner and more maintainable than what we've got, that PR will get some attention.
