### ISSUE TITLE
TLS (Client did not present a certificate)

### ISSUE THREAD

**Issue by surf-around** [haraka/Haraka#2693]
Using Haraka for outgoing mails.
Installed Let's Encrypt certificates in tls.ini config file.
both in main and [outbound] sections of config file key=tls_key.pem _(privkey.pem)_
cert=tls_cert.pem _(fullchain.pem)_
Also 3 certificates combined in single file in **config/tls** folder.

Tested the installation with  openssl s_client -connect localhost:25 -starttls smtp
Looks like OK.. Emails are relayed fine.

> [outbound] Trying TLS for domain: receiving_dom.com, host: 222.222.222.222
> [outbound] C: STARTTLS
> [outbound] S: 220 Go ahead\r\n
> [core] client TLS upgrade in progress, awaiting secured.
> [core] client TLS secured.
> [outbound] secured verified=true cipher=ECDHE-RSA-AES128-GCM-SHA256 version=TLSv1/SSLv3 cn=mx.yandex.net organization="Yandex LLC" issuer="Yandex LLC" expires="Nov 27 07:21:48 2019 GMT" fingerprint=B1:1C:5A:9A:93:1D:58:D7:4E:69:75:A0:DC:9E:9E:82:F0:46:75:8F
> .................
> [outbound]  delivered file=156 domain=receiving_dom.com host=mx.yandex.net ip=222.222.222.222 port=25 mode=SMTP tls=Y auth=N response="Ok: queued on mail.yandex.net as 7346831" delay=3.875 fails=0 rcpts=1/0/0

But the receiving mail server adds following header in the mail.
```
Received: from sending_dom.com (sending_dom.com [111.111.111.111])
	by mail.yandex.net (nwsmtp/Yandex) with ESMTPS id se0m3ws
	Sun, 01 Sep 2019 17:00 +0300
	(using TLSv1.2 with cipher ECDHE-RSA-AES128-GCM-SHA256 (128/128 bits))
	(Client certificate not present)
```
Similar certificate warning received from other servers too.
```
	(using TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 256/256 bits)
	(Client did not present a certificate)
	by CMGW with ESMTP
```
This problem did not happed with self signed certificates.
### system info
Haraka | Haraka.js — Version: 2.8.24
 --- | :--- 
Node | v10.16.2
OS | Linux 4.19
openssl | OpenSSL 1.0.2r

**Comment by surf-around** [comment]
It may be about Implementing Mutual SSL Authentication.
Receiving server's certificates are used for encryption and authentication.
But some receiving email servers demand mutual authentication by asking sending servers (Haraka) certificates.
Here are a few links related to this subject:
[Wikipedia](https://en.m.wikipedia.org/wiki/Mutual_authentication)
[Implementing Mutual SSL Authentication in Nodejs.](https://blog.cloudboost.io/implementing-mutual-ssl-authentication-fc20ab2392b3)
[Postfix at Stackoverflow](https://serverfault.com/questions/910882/client-did-not-present-a-certificate-postfix)
[Oracle](https://docs.oracle.com/cd/E19798-01/821-1841/bncbt/index.html)

**Comment by msimerson** [comment]
I did most of the recent work on our TLS implementation. I refactored and rewrote most of it to encapsulate it better, make it more testable, and then add some server-side features I needed like SNI support. What I didn't consider at all was client side and presenting a client certificate, although the work I did makes that easier (it loads all the TLS certs up and sets up their context). I imagine to add this, you'd want to identify the "main" domain that a connection is delivering mail on behalf of, see if a local cert is present for that domain. If so, use it, if not, use the servers default client certificate.

A PR implementing this behavior is welcome.

**Comment by celesteking** [comment]
mTLS requires quite an effort on both sides. It's funny how people think that just having a non-expired client certificate will make them immediately secure. There are other things, like cert issued by a trusted CA, like usage check, like rDNS.

Having a random comment set in a header by random MSP is neither a problem, nor a "warning" (as you stated), nor an issue you have to care about.

**Comment by gramakri** [comment]
I ran into a curious issue today. Haraka was unable to deliver to mail to a specific mail server. Investigating further, it's because the TLS connection simply does not finish. However, swaks just works fine.

```
[DEBUG] [-] [core] client TLS upgrade in progress, awaiting secured.
[ERROR] [8B8E0D82-25CB-4592-A1B0-EDE04C61C9AA.1.1] [outbound] Ongoing connection failed to xxxxxx:25 : Error: Client network socket disconnected before secure TLS connection was established
```

On further investigation, I found that this the connection does not finish when `key` and `cert` are sent. If I remove the key and cert for outbound tls, the connection works fine. Note that key and cert are valid LE certs. Also note that this issue only happens with a specific mail server (!).

@msimerson @celesteking I don't know how mTLS works but how is it possible that connection only fails when presenting valid certs? In general, is it required to send certs at all for outbound ? Can https://github.com/haraka/Haraka/blob/3e779b00b554e54fd8b1151e7af0734961007f2b/tls_socket.js#L709 be removed below? I thought sending certs is only required if the server requests certs. Why would server request client certs in SMTP world? I am referring to the code below:

```
        if (exports.tls_valid) {
            options = Object.assign(options, certsByHost['*']);
        }
```

Finally, I guess http://haraka.github.io/plugins/tls/#inbound-specific-configuration is obsolete ? AFAICT, there is no such thing as outbound and inbound section anymore in the code. I can submit a PR for this.

**Comment by gramakri** [comment]
I wrote some dummy code to test the whole TLS thing outside of haraka - https://git.girish.in/hacks/starttls/src/master/starttls.js . In the tls socket options if I set the key and cert in https://git.girish.in/hacks/starttls/src/master/starttls.js#L18, the TLS connection fails with ECONNRESET. (Also, note that https://git.girish.in/hacks/starttls/src/master/starttls.js#L6 is not the problematic mail server!). If you want to know the mail server, I will have to maybe email you or something (it's not a server I control, it's of a govt organization).

Just mentioning this, because it seems to be something TLS related and we probably have to fix how Haraka configures node accordingly.

**Comment by celesteking** [comment]
try `openssl s_client` with relevant parameters on the machine where that's failing, let's see what it shows

**Comment by msimerson** [comment]
> In general, is it required to send certs at all for outbound?

Only if the remote server asks for it. When Haraka is on the server side, that's when the options requestCert and rejectUnauthorized come into play. IIRC.

> how is it possible that connection only fails when presenting valid certs

My first guess: the remote server accepts authorized certs as a form of authentication and doesn't acknowledge the LE certs as "authorized."  Probably because only certs authorized by an internal CA would pass.

> Finally, I guess http://haraka.github.io/plugins/tls/#inbound-specific-configuration is obsolete

Correct.

**Comment by gramakri** [comment]
> My first guess: the remote server accepts authorized certs as a form of authentication and doesn't acknowledge the LE certs as "authorized." Probably because only certs authorized by an internal CA would pass.

Indeed, that seems to be the case. When certs are passed in, it tries to do client cert validation and it fails.

In fact, I found that http://www.postfix.org/TLS_README.html#client_cert_key says "Do not configure Postfix SMTP client certificates unless you must present client TLS certificates to one or more servers. Client certificates are not usually needed, and can cause problems in configurations that work well without them.".

To make some guesses here: If we configure postfix with client side certs, then postfix will send them. This in turn means that maybe TLS protocol has no way to actually know if certs are needed by the other side or not i.e they are sent anyway but maybe they are not used by the other end.

This matches the behavior I am seeing with Haraka/nodejs.

@msimerson The issue is when Haraka is the client and relaying mail. The code here https://github.com/haraka/Haraka/blob/3e779b00b554e54fd8b1151e7af0734961007f2b/tls_socket.js#L709

The above code gets used by the outbound tls and Haraka sets the key/cert properties. It seems nodejs sends the key/cert anway and the server I am dealing with will reject it since it doesn't recognize them. With that in mind, do you think we can add a setting in tls.ini that says "do not send client certs", similar to leaving all the keys empty in postfix? For example, `sendCert=false`.

I will submit a PR shortly.

**Comment by msimerson** [comment]
> Do you think we can add a setting in tls.ini that says "do not send client certs", similar to leaving all the keys empty in postfix? For example, sendCert=false

That seems to lack granularity. What happens if you are currently using `sendCert=true` to auth with a particular server and you need it disabled to connect and send outbound to another like this one in your case?

Sending TLS client certificates strikes me as an edge case. Let's treat it as one. When acting as the client, our default behavior is to not send TLS certificates. The exception is for hosts listed in the tls.ini file in a section named `tls_client_cert_hosts`, or something like that.

**Comment by msimerson** [comment]
Names are hard. What should that config section be named?
- hosts_that_require_tls_client_certs
- send_tls_client_certs_only_to_these_hosts
- ???

**Comment by gramakri** [comment]
@msimerson Oh, I went with your first suggestion `tls_client_cert_hosts`, except it's `no_tls_client_cert_hosts` to keep the existing behavior (which is to send the certs).

**Comment by msimerson** [comment]
Briefly summarized:

- sending TLS client certs sometimes results in TLS failures
- [MTLS](https://stackoverflow.com/questions/19601420/mtls-mutual-tls-details) is an unusual / rare use case in MTAs
- our choices are:
    - preserve existing send behavior and force Haraka users to disable it after they notice failures (hard to discover)
    - disable sending by default and force Haraka users that needs mTLS to enable it for specific hosts
    - other ???
- if some Well Known Sender was breaking TLS because Haraka sends client certs to it, many Haraka users would have to modify their configs to get TLS working with that WKS.
- conversely, if client sending is disabled by default and someone needs it, only that user needs to modify their config.

As much as I appreciate you preserving the existing behavior, one of those seems like a much better default to me than the other. I'd love for more of @haraka/core to chime in here.

**Comment by msimerson** [comment]
I wonder if outbound / client can determine if the server **wants** us to send our TLS client certificate and only send when the server asks. We'd still need the ability to disable sending for certain hosts that ask for mutual TLS but for which we don't have a valid cert.

**Comment by gene-hightower** [comment]
Superficial reading of the TLS 1.2 documentation suggests that's how it works: the server sends a "Certificate Request" message.

My personal SMTP server always asks for a client cert, and many mainstream email senders provide one; including Github (CN=*.smtp.github.com), and MS (CN=mail.protection.outlook.com), Linkedin (CN=mail.linkedin.com), Google (CN=smtp.gmail.com), and many others.

I typically configure my postfix outgoing servers to use a client cert and have only encountered problems when the CN did not match the FCrDNS name of the sending host.
That said, in <http://www.postfix.org/TLS_README.html#client_cert_key> wiser and more experienced people than me warn against using client certs.

**Comment by gramakri** [comment]
> As much as I appreciate you preserving the existing behavior

For the cloudron mail server, I actually disabled it now altogether with `no_tls_client_cert_hosts=*`. (this is why added the wildcard logic as well). So, I am perfectly fine with making that the default and renaming the property to `tls_client_cert_hosts`.

I tried to dig in more about the postfix warning but I can't understand _why_ it warns. I only found [this](http://postfix.1071664.n5.nabble.com/Configuring-smtp-tls-cert-file-for-specific-domain-td105177.html) which repeats the warning.

**Comment by gramakri** [comment]
@msimerson Let me know if you want to me to make it the default to not send the certs and add a `tls_client_cert_hosts` instead.

**Comment by msimerson** [comment]
>  Let me know if you want to me to make it the default to not send the certs 

I think an issue with your proposed implementation is that with `no_tls_client_cert_hosts=*` set, you can't *also* MTLS with a server that requires it. I'm like a solution that:

- does the right thing most of the time with no effort by the MTA admin
- we don't have to patch later because a config setting painted us into a corner.

I think perhaps the logic should be:

- if the remote is in the `mutual_auth_hosts` list in tls.ini, send the specified (or default) certificate
- if the remote is in the exclude list, don't send.
- otherwise: based on `mutual_tls` boolean.

Configured thusly, I can't think of a situation that isn't straight forward and easy to configure.

```ini
mutual_tls=false

; hosts that require us to present a cert signed by a CA we both trust
[mutual_auth_hosts]
xo.huggable.gov=special.my-tld.com

; these hosts request mutual TLS and reject our TLS certificate
[mutual_auth_hosts_exclude]
bofh.no-such-agency.gov
```

**Comment by gramakri** [comment]
@msimerson I have to admit I don't have the setup to test mutual TLS. I fear that testing all these combinations is a lot of work with little use since I am not sure who wants this. I think the existing code is actually a bug that it sends certs (rather a quirk in nodejs behavior+tls). The easiest fix I can think of is removing sending of the client certs altogether. If someone wants it, we can possibly add all these options. 

So, if it's ok, we can simply remove those 2 lines code at  https://github.com/haraka/Haraka/blob/master/tls_socket.js#L710 . Do you see any value in keeping that code?

**Comment by msimerson** [comment]
> The easiest fix I can think of is removing sending of the client certs altogether

If we knew this wouldn't result in problems, I'd agree. It's been too long since I dug in and don't have time now to go digging around in the node's TLS internals to refresh my memory on exactly how the TLS negotiation works. Maybe changing this behavior will be better for everyone. I just feel better about it knowing that if it does cause someone grief, they've got a config setting they can twiddle instead of having to monkey patch their Haraka until we get around to reverting the change. Take a look at #2902 and let me know what you think.
