### ISSUE TITLE
secureConnection event listener registration error

### ISSUE THREAD

**Issue by emarteca** [haraka/Haraka#2743]
Hi all, I've been working on a tool to identify instances of events registered to the wrong object in uses of some JavaScript event-driven APIs, as part of a research project.
The tool flagged line 64 in tls_socket.js (in the repo's root directory), on the registration of the listener for "secureConnection": https://github.com/haraka/Haraka/blob/master/tls_socket.js#L64

The reason I believe this is an error is as follows (from looking at the nodejs tls API documentation, particularly https://nodejs.org/api/tls.html#tls_class_tls_tlssocket):
"secureConnection" is an event on tls.Server, but the listener for it here is a tls.TLSSocket.
TLSSocket has an event "secureConnect", so my guess is that the code here should instead be "self.targetsocket.on('secureConnect', ..."

Thanks!

**Comment by celesteking** [comment]
Well this is one mess of a code. I spent 1 hr debugging and trying to understand all this and it seems like https://github.com/haraka/Haraka/blob/master/tls_socket.js#L64 is never fired.

In both cases 'secure' event will be fired on `cleartext` socket (and also at https://github.com/haraka/Haraka/blob/master/tls_socket.js#L68 ). That isn't documented in node docs, but it is clearly seen in their source code.

In order to proceed with TLS setup, we rely on this 'secure' event in server part of code: https://github.com/haraka/Haraka/blob/master/tls_socket.js#L659
and on 'secureConnect' in client part: https://github.com/haraka/Haraka/blob/master/tls_socket.js#L723

This "code base" really needs to be rewritten by someone smart, either to consistently utilize undocumented event 'secure' both for client and server, or documented 'secureConnect' on client and something else (?) in the server part (we don't use `tls.Server` which would emit 'secureConnection').
