### ISSUE TITLE
Scalling and monitor the outbound server and outbound Queue

### ISSUE THREAD

**Issue by ajay-psd** [haraka/Haraka#2943]
Hi! I am using Haraka outbound mail server for long time now. For small scale 30K a day.
Now we have some requirement where we need to send emails on a very High Scale.

1. Is there any benchmark published avalible? how may email ((max 10MB attachment)) can be processed and deliver by Haraka machine 1 AWS c3.medium 4core system, and what is ideal Max concurrency limit we should have for outbound. 

2.How do we monitor the outbound Queue, is there any plugin available? I tried to check but not got much details on it.

3. Is there any reference of for best practices guidelines for implementing Haraka for High scale email.
runing cluster mode(node=cpus).

Kindly suggest.

**Comment by wioxjk** [comment]
In order to monitor the queue on my servers - I am just monitoring the number of files present in the "queue" catalogue.
Problably not the most ideal way, but it works atleast for now.

**Comment by baudehlo** [comment]
1. No recent benchmarks, but I managed to get it to receive about 5000
emails a second 11 years ago on the hardware available then. I haven't
benchmarked Outbound since it depends on so many factors.

2. The main `haraka` binary has a --qstat option, there's also the
excellent `process_title` plugin which helps with monitoring things.

3. Regarding scaling, there's a wiki page:
https://github.com/haraka/Haraka/wiki/Performance-Tuning
