### ISSUE TITLE
Outbound loop when local recipient replies to bounce/daemon email

### ISSUE THREAD

**Issue by DoobleD** [haraka/Haraka#3065]
When a local recipient replies to a bounce email (i.e. an email sent from MAILER-DAEMON@{me}), we apparently end up in the same local host loop issue as described in https://github.com/haraka/Haraka/issues/2809.

Haraka delivers to itself and relays via outbound again and again until it reaches some threshold.

Is there a way to prevent that? Maybe there is a setting to drop/forbid replies to a daemon email?

**Comment by Shubhanshuarya** [comment]
This same thing happening in inbound mails also.  Haraka delivers to itself again and again. Is ithere any solution?

**Comment by msimerson** [comment]
The issue @DoobleD is seeing is because `connection.relaying=true` is set on an inbound connection. Haraka's default queue selection is binary: outbound when `connection.relaying=true` and inbound for all else. This is often insufficient, especially when we consider transactions with local *and* remote recipients.

In this case, Haraka outbound looks up the MX, connects to the destination IP address (itself), and delivers the message.

IMO, [The Right Way](https://www.youtube.com/watch?v=dQw4w9WgXcQ) to solve this issue is to assure that one of your plugins (queue or recipient validation) has a `get_mx` hook that provides outbound with more specific (than DNS) routes for your local domains. Plugins that have this mechanism built-in are `queue/smtp_forward` and [haraka-plugin-qmail-deliverable](https://github.com/haraka/haraka-plugin-qmail-deliverable).
